OrdererOrgs:
  - Name: Orderer
    Domain: certification-network.com
    Specs:
      - Hostname: orderer
PeerOrgs:
 - Name: aktu
   Domain: aktu.certification-network.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 1
      
 - Name: upgov
   Domain: upgov.certification-network.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 1
 - Name: mgm
   Domain: mgm.certification-network.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 1
